"""Description of changes

Revision ID: 662f3a682225
Revises: 
Create Date: 2025-10-14 15:50:34.330401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '662f3a682225'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employment_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('experience_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('min_years', sa.Integer(), nullable=True),
    sa.Column('max_years', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('categories', 'color_code',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_companies_name_text', table_name='companies', postgresql_using='gin')
    op.drop_index('idx_companies_name_trgm', table_name='companies', postgresql_using='gin')
    op.drop_index('idx_companies_normalized_name', table_name='companies')
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'logo_url')
    op.drop_column('companies', 'size_range')
    op.drop_column('companies', 'description')
    op.add_column('locations', sa.Column('remote_ok', sa.Boolean(), nullable=True))
    op.add_column('locations', sa.Column('total_jobs', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('avg_salary', sa.Integer(), nullable=True))
    op.alter_column('locations', 'city',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('locations', 'region',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('locations', 'country',
               existing_type=sa.VARCHAR(length=100),
               server_default=None,
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_locations_city', table_name='locations')
    op.drop_constraint('locations_city_key', 'locations', type_='unique')
    op.drop_column('locations', 'longitude')
    op.drop_column('locations', 'latitude')
    op.drop_column('locations', 'timezone')
    op.alter_column('raw_jobs', 'location',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Raw location text from scraper (e.g., "Auckland CBD, Auckland")',
               existing_nullable=True)
    op.alter_column('raw_jobs', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('raw_jobs', 'processed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('raw_jobs', 'processed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_raw_jobs_company', table_name='raw_jobs')
    op.drop_index('idx_raw_jobs_location', table_name='raw_jobs')
    op.drop_index('idx_raw_jobs_processed', table_name='raw_jobs')
    op.drop_index('idx_raw_jobs_scraped_at', table_name='raw_jobs')
    op.drop_index('idx_raw_jobs_search_term', table_name='raw_jobs')
    op.drop_index('idx_raw_jobs_url', table_name='raw_jobs')
    op.alter_column('scraping_sessions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('scraping_sessions', 'jobs_collected',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('scraping_sessions', 'pages_scraped',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('scraping_sessions', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('skill_trends', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('skill_trends', 'job_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('skill_trends', 'new_jobs_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_skill_trends_date', table_name='skill_trends')
    op.drop_index('idx_skill_trends_demand_score', table_name='skill_trends')
    op.drop_index('idx_skill_trends_skill_date', table_name='skill_trends')
    op.drop_constraint('skill_trends_skill_id_date_recorded_key', 'skill_trends', type_='unique')
    op.drop_constraint('skill_trends_skill_id_fkey', 'skill_trends', type_='foreignkey')
    op.create_foreign_key(None, 'skill_trends', 'skills', ['skill_id'], ['id'])
    op.drop_column('skill_trends', 'created_at')
    op.add_column('skills', sa.Column('subcategory', sa.Text(), nullable=True))
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('skills', 'category',
               existing_type=postgresql.ENUM('programming_language', 'framework', 'library', 'database', 'cloud_platform', 'tool', 'methodology', 'soft_skill', 'certification', name='skill_category'),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('skills', 'popularity_score',
               existing_type=sa.INTEGER(),
               server_default=None,
               type_=sa.DECIMAL(precision=3, scale=2),
               existing_nullable=True)
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_skills_name_text', table_name='skills', postgresql_using='gin')
    op.drop_index('idx_skills_name_trgm', table_name='skills', postgresql_using='gin')
    op.drop_column('skills', 'aliases')
    op.drop_column('skills', 'skill_type')
    op.drop_column('skills', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('skill_type', postgresql.ENUM('technical', 'soft', 'certification', 'methodology', name='skill_type'), server_default=sa.text("'technical'::skill_type"), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('aliases', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('idx_skills_name_trgm', 'skills', ['name'], unique=False, postgresql_using='gin')
    op.create_index('idx_skills_name_text', 'skills', [sa.text("to_tsvector('english'::regconfig, name::text)")], unique=False, postgresql_using='gin')
    op.alter_column('skills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('skills', 'popularity_score',
               existing_type=sa.DECIMAL(precision=3, scale=2),
               server_default=sa.text('0'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('skills', 'category',
               existing_type=sa.Text(),
               type_=postgresql.ENUM('programming_language', 'framework', 'library', 'database', 'cloud_platform', 'tool', 'methodology', 'soft_skill', 'certification', name='skill_category'),
               nullable=True)
    op.alter_column('skills', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('skills', 'subcategory')
    op.add_column('skill_trends', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'skill_trends', type_='foreignkey')
    op.create_foreign_key('skill_trends_skill_id_fkey', 'skill_trends', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('skill_trends_skill_id_date_recorded_key', 'skill_trends', ['skill_id', 'date_recorded'])
    op.create_index('idx_skill_trends_skill_date', 'skill_trends', ['skill_id', 'date_recorded'], unique=False)
    op.create_index('idx_skill_trends_demand_score', 'skill_trends', [sa.text('demand_score DESC')], unique=False)
    op.create_index('idx_skill_trends_date', 'skill_trends', ['date_recorded'], unique=False)
    op.alter_column('skill_trends', 'new_jobs_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('skill_trends', 'job_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('skill_trends', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('scraping_sessions', 'status',
               existing_type=sa.TEXT(),
               server_default=sa.text("'running'::text"),
               existing_nullable=True)
    op.alter_column('scraping_sessions', 'pages_scraped',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('scraping_sessions', 'jobs_collected',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('scraping_sessions', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.create_index('idx_raw_jobs_url', 'raw_jobs', ['url'], unique=False)
    op.create_index('idx_raw_jobs_search_term', 'raw_jobs', ['search_term'], unique=False)
    op.create_index('idx_raw_jobs_scraped_at', 'raw_jobs', ['scraped_at'], unique=False)
    op.create_index('idx_raw_jobs_processed', 'raw_jobs', ['processed'], unique=False)
    op.create_index('idx_raw_jobs_location', 'raw_jobs', ['location'], unique=False)
    op.create_index('idx_raw_jobs_company', 'raw_jobs', ['company'], unique=False)
    op.alter_column('raw_jobs', 'processed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('raw_jobs', 'processed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('raw_jobs', 'scraped_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.alter_column('raw_jobs', 'location',
               existing_type=sa.TEXT(),
               comment='Raw location text from scraper (e.g., "Auckland CBD, Auckland")',
               existing_nullable=True)
    op.add_column('locations', sa.Column('timezone', sa.VARCHAR(length=50), server_default=sa.text("'Pacific/Auckland'::character varying"), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('latitude', sa.NUMERIC(precision=10, scale=8), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('longitude', sa.NUMERIC(precision=11, scale=8), autoincrement=False, nullable=True))
    op.create_unique_constraint('locations_city_key', 'locations', ['city'])
    op.create_index('idx_locations_city', 'locations', ['city'], unique=False)
    op.alter_column('locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('locations', 'country',
               existing_type=sa.Text(),
               server_default=sa.text("'New Zealand'::character varying"),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('locations', 'region',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('locations', 'city',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('locations', 'avg_salary')
    op.drop_column('locations', 'total_jobs')
    op.drop_column('locations', 'remote_ok')
    op.add_column('companies', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('size_range', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_index('idx_companies_normalized_name', 'companies', ['normalized_name'], unique=False)
    op.create_index('idx_companies_name_trgm', 'companies', ['name'], unique=False, postgresql_using='gin')
    op.create_index('idx_companies_name_text', 'companies', [sa.text("to_tsvector('english'::regconfig, name::text)")], unique=False, postgresql_using='gin')
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('companies', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=True)
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('categories', 'color_code',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_table('experience_levels')
    op.drop_table('employment_types')
    # ### end Alembic commands ###
